baseURL = "https://beiertu-mms.github.io"
title   = "Tung Beier"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10
copyright = "This work is licensed under the MIT License." # This message is only used by the RSS template.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Tung Beier"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  description = "Tung Beier's landing page"
  keywords = ""
  images = [""]

  homeSubtitle = "A backend engineer specializing in JVM and Cloud technologies."

  disableReadOtherPosts = false
  enableThemeToggle = true
  enableSharingButtons = true
  enableGlobalLanguageMenu = true
  customCSS = []
  customJS  = []
  justifyContent = true

  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd "
    logoHomeLink = "/"

  [params.commento]
    url = ""

  [[params.social]]
    name = "email"
    url  = "mailto:tung.beier@gmx.de"

  [[params.social]]
    name = "github"
    url  = "https://github.com/beiertu-mms"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/tung-beier/"

[languages]
  [languages.en]
    [languages.en.params]
      subtitle  = "Hello Friend NG Theme"
      weight    = 1
      copyright = '<a href="https://github.com/beiertu-mms/beiertu-mms.github.io/blob/master/LICENSE" target="_blank" rel="noopener">MIT</a>'

