---
name: 'Run Renovate'
"on":
  schedule:
    - cron: '0 6 * * 1-5' # https://crontab.guru/#0_6_*_*_1-5
  push:
    branches:
      - "master"
    paths:
      - ".github/renovate.json"
      - ".github/workflows/run-renovate.yaml"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
