---
name: Update Themes
"on":
  schedule:
    - cron: '0 7 * * 1' # At 07:00 on Monday
  workflow_dispatch:

jobs:
  update_themes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule update --recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        env:
          bot_name: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/themes/update-sub-modules
          delete-branch: true
          reviewers: beiertu-mms
          committer: ${{ env.bot_name }}
          author: ${{ env.bot_name }}
          commit-message: 'chore(themes): update sub-modules'
          title: 'chore(themes): update sub-modules'
          labels: dependencies
          body: |
            Update the [themes](https://github.com/beiertu-mms/beiertu-mms.github.io/tree/master/themes) submodules.
