---
name: Update Themes
"on":
  schedule:
    - cron: '0 7 * * 1' # At 07:00 on Monday
  workflow_dispatch:

jobs:
  update_themes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule update --recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          branch: chore/themes/update-sub-modules
          commit-message: 'chore(themes): update sub-modules'
          title: 'chore(themes): update sub-modules'
          body: |
            Update the [themes](https://github.com/beiertu-mms/beiertu-mms.github.io/tree/master/themes) submodules.
          reviewers: beiertu-mms
          assignees: beiertu-mms

